name: Sync to 53
on:
  push:
    branches:
    - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    -name: Checkout Repository
    uses: actions/checkout@v3
    -name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v2
  with:
    aws-access-key-id: ${{ secrets.AWS ACCESS_KEY}}
    ans-secret-access-key: ${{secrets.AWS SECRET_KEY }}
    aws-region: eu-north-1
  name: Sync to 53
  run: ans s3 sync. s3://bucketshari
